<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('movies', function (Blueprint $table) {

            DB::table('movies')->insert([
                
                ['title_movie' => 'Avatar', 'description_movie' => 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home', 'release_date' => '2009-12-16', 'duration' => '2 hr 42 min', 'image' => 'Avatar.jpg', 'trailler' => 'https://www.youtube.com/embed/5PSNL1qE6VY?si=nP3nnfn9G1sODHQi', 'calification' => 4.6],
                ['title_movie' => 'Avengers: Endgame', 'description_movie' => 'After the devastating events of Avengers  - Infinity War the universe is in ruins With the help of remaining allies the Avengers assemble once more in order to reverse Thanos actions and restore balance to the universe', 'release_date' => '2019-05-24', 'duration' => '3 hr 1 min', 'image' => 'Avengers_Endgame.jpg', 'trailler' => 'https://www.youtube.com/embed/znk2OICHbjY?si=kBUaplQGGIyCmHC-', 'calification' => 4.1],
                ['title_movie' => 'Avatar: The Way of Water', 'description_movie' => 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora Once a familiar threat returns to finish what was previously started Jake must work with Neytiri and the army of the Navi race to protect their home', 'release_date' => '2019-05-24', 'duration' => '3 hr 1 min', 'image' => 'Avatar_The_Way_of_Water.jpg', 'trailler' => 'https://www.youtube.com/embed/o5F8MOz_IDw?si=yZ0jq6IQG71CIFnq', 'calification' => 4.7],
                ['title_movie' => 'Titanic', 'description_movie' => 'A seventeen year old aristocrat falls in love with a kind but poor artist aboard the luxurious ill fated RMS Titanic', 'release_date' => '1997-12-19', 'duration' => '3 hr 14 min', 'image' => 'Titanic.jpg', 'trailler' => 'https://www.youtube.com/embed/tA_qMdzvCvk?si=qNg5Wip0iztjMsvR', 'calification' => 4.1],
                ['title_movie' => 'Star Wars: Episode VII - The Force Awakens', 'description_movie' => 'As a new threat to the galaxy rises Rey a desert scavenger and Finn an ex stormtrooper must join Han Solo and Chewbacca to search for the one hope of restoring peace', 'release_date' => '2015-12-16', 'duration' => '2 hr 18 min', 'image' => 'Star_Wars_Episode_VII__The_Force_Awakens.jpg', 'trailler' => 'https://www.youtube.com/embed/sGbxmsDFVnE?si=jDbvLZMf10pcOw1k', 'calification' => 4.6],
                ['title_movie' => 'Avengers: Infinity War', 'description_movie' => 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe', 'release_date' => '2015-12-16', 'duration' => '2 hr 18 min', 'image' => 'Avengers_Infinity_War.jpg', 'trailler' => 'https://www.youtube.com/embed/6ZfuNTqbHE8?si=qmm-Hlbi50i5Jjob', 'calification' => 5],
                ['title_movie' => 'Spider-Man: No Way Home', 'description_movie' => 'With Spider Mans identity now revealed Peter asks Doctor Strange for help When a spell goes wrong dangerous foes from other worlds start to appear forcing Peter to discover what it truly means to be Spider Man', 'release_date' => '2015-12-16', 'duration' => '2 hr 18 min', 'image' => 'SpiderMan_No_Way_Home.jpg', 'trailler' => 'https://www.youtube.com/embed/JfVOs4VSpmA?si=pA92bsFZAKak-wa0', 'calification' => 3.1],
                ['title_movie' => 'Jurassic World', 'description_movie' => 'A new theme park built on the original site of Jurassic Park creates a genetically modified hybrid dinosaur the Indominus Rex which escapes containment and goes on a killing spree', 'release_date' => '2015-06-10', 'duration' => '2 hr 4 min', 'image' => 'Jurassic_World.jpg', 'trailler' => 'https://www.youtube.com/embed/RFinNxS5KN4?si=AF8DqvVwdhwb3ADx', 'calification' => 3.4],
                ['title_movie' => 'The Lion King', 'description_movie' => 'After the murder of his father a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery', 'release_date' => '2019-07-11', 'duration' => '1 hr 58 min', 'image' => 'The_Lion_King.jpg', 'trailler' => 'https://www.youtube.com/embed/7TavVZMewpY?si=8PLT4hUJ70gnnaox', 'calification' => 4.1],
                ['title_movie' => 'The Avengers', 'description_movie' => 'Earths mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity', 'release_date' => '2012-05-25', 'duration' => '2 hr 23 min', 'image' => 'The_Avengers.jpg', 'trailler' => 'https://www.youtube.com/embed/eOrNdBpGMv8?si=on6-zU30bPABaS6E', 'calification' => 4.7],
                ['title_movie' => 'Furious 7', 'description_movie' => 'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother', 'release_date' => '2015-05-01', 'duration' => '2 hr 17 min', 'image' => 'Furious_7.jpg', 'trailler' => 'https://www.youtube.com/embed/Skpu5HaVkOc?si=DwQxaNyQdp01uXaB', 'calification' => 4.2],
                ['title_movie' => 'Top Gun: Maverick', 'description_movie' => 'After thirty years Maverick is still pushing the envelope as a top naval aviator but must confront ghosts of his past when he leads TOP GUNs elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it', 'release_date' => '2015-05-01', 'duration' => '2 hr 17 min', 'image' => 'Top_Gun_Maverick.jpg', 'trailler' => 'https://www.youtube.com/embed/qSqVVswa420?si=I7RTHuC41ljepwQn', 'calification' => 3.2],
                ['title_movie' => 'Frozen II', 'description_movie' => 'Anna Elsa Kristoff Olaf and Sven leave Arendelle to travel to an ancient autumn bound forest of an enchanted land They set out to find the origin of Elsas powers in order to save their kingdom', 'release_date' => '2019-11-20', 'duration' => '1 hr 43 min', 'image' => 'Frozen_II.jpg', 'trailler' => 'https://www.youtube.com/embed/Zi4LMpSDccc?si=HnHmdNVNfiFumoAY', 'calification' => 3.3],
                ['title_movie' => 'Barbie', 'description_movie' => 'Barbie suffers a crisis that leads her to question her world and her existence', 'release_date' => '2019-11-20', 'duration' => '1 hr 43 min', 'image' => 'Barbie.jpg', 'trailler' => 'https://www.youtube.com/embed/pBk4NYhWNMM?si=lS2gJP_OgSyuN4Lb', 'calification' => 4.3],
                ['title_movie' => 'Avengers: Age of Ultron', 'description_movie' => 'When Tony Stark and Bruce Banner try to jump start a dormant peacekeeping program called Ultron things go horribly wrong and its up to Earths mightiest heroes to stop the villainous Ultron from enacting his terrible plan', 'release_date' => '2015-05-22', 'duration' => '2 hr 21 min', 'image' => 'Avengers_Age_of_Ultron.jpg', 'trailler' => 'https://www.youtube.com/embed/tmeOjFno6Do?si=9Ks_-Kk0CgFAqKgb', 'calification' => 3.5],
                ['title_movie' => 'The Super Mario Bros. Movie', 'description_movie' => 'A plumber named Mario travels through an underground labyrinth with his brother Luigi trying to save a captured princess', 'release_date' => '2015-05-22', 'duration' => '2 hr 21 min', 'image' => 'The_Super_Mario_Bros_Movie.jpg', 'trailler' => 'https://www.youtube.com/embed/TnGl01FkMMo?si=6iXtHTgN123vLtl1', 'calification' => 4.8],
                ['title_movie' => 'Black Panther', 'description_movie' => 'TChalla heir to the hidden but advanced kingdom of Wakanda must step forward to lead his people into a new future and must confront a challenger from his countrys past', 'release_date' => '2015-05-22', 'duration' => '2 hr 21 min', 'image' => 'Black_Panther.jpg', 'trailler' => 'https://www.youtube.com/embed/xjDjIWPwcPU?si=R46awihwxXvjnoSa', 'calification' => 4.3],
                ['title_movie' => 'Harry Potter and the Deathly Hallows: Part 2', 'description_movie' => 'Harry Ron and Hermione search for Voldemorts remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts', 'release_date' => '2015-05-22', 'duration' => '2 hr 21 min', 'image' => 'Harry_Potter_and_the_Deathly_Hallows_Part_2.jpg', 'trailler' => 'https://www.youtube.com/embed/5NYt1qirBWg?si=L1uaswljnsaJgQBT', 'calification' => 4.9],
                ['title_movie' => 'Star Wars: Episode VIII - The Last Jedi', 'description_movie' => 'The Star Wars saga continues as new heroes and galactic legends go on an epic adventure unlocking mysteries of the Force and shocking revelations of the past', 'release_date' => '2017-12-13', 'duration' => '2 hr 32 min', 'image' => 'Star_Wars_Episode_VIII__The_Last_Jedi.jpg', 'trailler' => 'https://www.youtube.com/embed/Q0CbN8sfihY?si=vjxp3lsWXTqSUdKm', 'calification' => 3.7],
                ['title_movie' => 'Jurassic World: Fallen Kingdom', 'description_movie' => 'When the islands dormant volcano begins roaring to life Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction level event', 'release_date' => '2018-06-06', 'duration' => '2 hr 8 min', 'image' => 'Jurassic_World_Fallen_Kingdom.jpg', 'trailler' => 'https://www.youtube.com/embed/vn9mMeWcgoM?si=TnkmpJSVb6sPLuf_', 'calification' => 3.6],
                ['title_movie' => 'Frozen', 'description_movie' => 'When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter her sister Anna teams up with a mountain man his playful reindeer and a snowman to change the weather condition', 'release_date' => '2013-11-22', 'duration' => '1 hr 42 min', 'image' => 'Frozen.jpg', 'trailler' => 'https://www.youtube.com/embed/TbQm5doF_Uc?si=lRyFdgyG5je_fmFW', 'calification' => 3.8],
                ['title_movie' => 'Beauty and the Beast', 'description_movie' => 'A selfish Prince is cursed to become a monster for the rest of his life unless he learns to fall in love with a beautiful young woman he keeps prisoner', 'release_date' => '2017-03-16', 'duration' => '2 hr 9 min', 'image' => 'Beauty_and_the_Beast.jpg', 'trailler' => 'https://www.youtube.com/embed/e3Nl_TCQXuw?si=wsXXcT791SM8qsPy', 'calification' => 4],
                ['title_movie' => 'Incredibles 2', 'description_movie' => 'The Incredibles family takes on a new mission which involves a change in family roles  - Bob Parr (Mr Incredible) must manage the house while his wife Helen (Elastigirl) goes out to save the world', 'release_date' => '2017-03-16', 'duration' => '2 hr 9 min', 'image' => 'Incredibles_2.jpg', 'trailler' => 'https://www.youtube.com/embed/i5qOzqD9Rms?si=aPSD89lkUiXw-B1R', 'calification' => 3.6],
                ['title_movie' => 'The Fate of the Furious', 'description_movie' => 'When a mysterious woman seduces Dominic Toretto into the world of terrorism and a betrayal of those closest to him the crew face trials that will test them as never before', 'release_date' => '2017-05-12', 'duration' => '2 hr 16 min', 'image' => 'The_Fate_of_the_Furious.jpg', 'trailler' => 'https://www.youtube.com/embed/JwMKRevYa_M?si=9hz-xGn1PWpzVOPX', 'calification' => 3.9],
                ['title_movie' => 'Iron Man 3', 'description_movie' => 'When Tony Starks world is torn apart by a formidable terrorist called the Mandarin he starts an odyssey of rebuilding and retribution', 'release_date' => '2013-05-24', 'duration' => '2 hr 10 min', 'image' => 'Iron_Man_3.jpg', 'trailler' => 'https://www.youtube.com/embed/Ke1Y3P9D0Bc?si=YWYWpNvzM5H4I2AZ', 'calification' => 4.2],
                ['title_movie' => 'Minions', 'description_movie' => 'Minions Stuart Kevin and Bob are recruited by Scarlet Overkill a supervillain who alongside her inventor husband Herb hatches a plot to take over the world', 'release_date' => '2015-05-09', 'duration' => '1 hr 31 min', 'image' => 'Minions.jpg', 'trailler' => 'https://www.youtube.com/embed/P9-FCC6I7u0?si=8ROAtF7YVl4aMQyK', 'calification' => 4],
                ['title_movie' => 'Captain America: Civil War', 'description_movie' => 'Political involvement in the Avengers affairs causes a rift between Captain America and Iron Man', 'release_date' => '2016-05-27', 'duration' => '2 hr 27 min', 'image' => 'Captain_America_Civil_War.jpg', 'trailler' => 'https://www.youtube.com/embed/dKrVegVI0Us?si=CRcsCXsIBaMfd1Wr', 'calification' => 4.8],
                ['title_movie' => 'Aquaman', 'description_movie' => 'Arthur Curry the human born heir to the underwater kingdom of Atlantis goes on a quest to prevent a war between the worlds of ocean and land', 'release_date' => '2016-05-27', 'duration' => '2 hr 27 min', 'image' => 'Aquaman.jpg', 'trailler' => 'https://www.youtube.com/embed/WDkg3h8PCVU?si=vV8FUBZ_gp6dSdhv', 'calification' => 3.4],
                ['title_movie' => 'The Lord of the Rings: The Return of the King', 'description_movie' => 'Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring', 'release_date' => '2003-12-17', 'duration' => '3 hr 21 min', 'image' => 'The_Lord_of_the_Rings_The_Return_of_the_King.jpg', 'trailler' => 'https://www.youtube.com/embed/r5X-hFf6Bwo?si=g4Fsn6OC5Hf4J_Yy', 'calification' => 3.3],
                ['title_movie' => 'Skyfall', 'description_movie' => 'James Bonds loyalty to M is tested when her past comes back to haunt her When MI6 comes under attack 007 must track down and destroy the threat no matter how personal the cost', 'release_date' => '2012-10-25', 'duration' => '2 hr 23 min', 'image' => 'Skyfall.jpg', 'trailler' => 'https://www.youtube.com/embed/6kw1UVovByw?si=8MWWLmRYowd6uenK', 'calification' => 3.9],
                ['title_movie' => 'Spider-Man: Far from Home', 'description_movie' => 'Following the events of Avengers  - Endgame Spider Man must step up to take on new threats in a world that has changed forever', 'release_date' => '2019-06-28', 'duration' => '2 hr 9 min', 'image' => 'SpiderMan_Far_from_Home.jpg', 'trailler' => 'https://www.youtube.com/embed/Nt9L1jCKGnE?si=35e_2NB-lf0q3ecX', 'calification' => 4.3],
                ['title_movie' => 'Captain Marvel', 'description_movie' => 'Carol Danvers becomes one of the universes most powerful heroes when Earth is caught in the middle of a galactic war between two alien races', 'release_date' => '2019-03-06', 'duration' => '2 hr 3 min', 'image' => 'Captain_Marvel.jpg', 'trailler' => 'https://www.youtube.com/embed/wS_qbDztgVY?si=f3E79mlkKZ0Uge34', 'calification' => 3.7],
                ['title_movie' => 'Transformers: Dark of the Moon', 'description_movie' => 'The Autobots learn of a Cybertronian spacecraft hidden on the moon and race against the Decepticons to reach it and to learn its secrets', 'release_date' => '2011-06-29', 'duration' => '2 hr 34 min', 'image' => 'Transformers_Dark_of_the_Moon.jpg', 'trailler' => 'https://www.youtube.com/embed/Rf3OcxIFbRE?si=E9Rb9Qfw4yhwlI9p', 'calification' => 3.1],
                ['title_movie' => 'Jurassic Park', 'description_movie' => 'A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the parks cloned dinosaurs to run loose', 'release_date' => '1993-06-11', 'duration' => '2 hr 7 min', 'image' => 'Jurassic_Park.jpg', 'trailler' => 'https://www.youtube.com/embed/lc0UehYemQA?si=ivJmd_aeSiVCI8rM', 'calification' => 3.3],
                ['title_movie' => 'Transformers: Age of Extinction', 'description_movie' => 'When humanity allies with a bounty hunter in pursuit of Optimus Prime the Autobots turn to a mechanic and his family for help', 'release_date' => '2014-06-25', 'duration' => '2 hr 45 min', 'image' => 'Transformers_Age_of_Extinction.jpg', 'trailler' => 'https://www.youtube.com/embed/T9bQCAWahLk?si=0a9VuqQnfR_XCaFv', 'calification' => 4.3],
                ['title_movie' => 'The Dark Knight Rises', 'description_movie' => 'Eight years after the Jokers reign of chaos Batman is coerced out of exile with the assistance of the mysterious Selina Kyle in order to defend Gotham City from the vicious guerrilla terrorist Bane', 'release_date' => '2012-07-19', 'duration' => '2 hr 44 min', 'image' => 'The_Dark_Knight_Rises.jpg', 'trailler' => 'https://www.youtube.com/embed/g8evyE9TuYk?si=su_X6v98KOEj9sUu', 'calification' => 3.1],
                ['title_movie' => 'Star Wars: Episode IX - The Rise of Skywalker', 'description_movie' => 'In the riveting conclusion of the landmark Skywalker saga new legends will be born and the final battle for freedom is yet to come', 'release_date' => '2019-12-18', 'duration' => '2 hr 21 min', 'image' => 'Star_Wars_Episode_IX__The_Rise_of_Skywalker.jpg', 'trailler' => 'https://www.youtube.com/embed/8Qn_spdM5Zg?si=UeT0AGNxEIgGCm-A', 'calification' => 4.5],
                ['title_movie' => 'Joker', 'description_movie' => 'During the 1980s a failed stand up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure', 'release_date' => '2019-10-02', 'duration' => '2 hr 2 min', 'image' => 'Joker.jpg', 'trailler' => 'https://www.youtube.com/embed/t433PEQGErc?si=7X-6MbcGcYayOWzk', 'calification' => 4],
                ['title_movie' => 'Toy Story 4', 'description_movie' => 'When a new toy called "Forky" joins Woody and the gang a road trip alongside old and new friends reveals how big the world can be for a toy', 'release_date' => '2019-06-20', 'duration' => '1 hr 40 min', 'image' => 'Toy_Story_4.jpg', 'trailler' => 'https://www.youtube.com/embed/wmiIUN-7qhE?si=uStiltukjmlPyap1', 'calification' => 4.3],
                ['title_movie' => 'Toy Story 3', 'description_movie' => 'The toys are mistakenly delivered to a day care center instead of the attic right before Andy leaves for college and its up to Woody to convince the other toys that they werent abandoned and to return home', 'release_date' => '2010-06-16', 'duration' => '1 hr 43 min', 'image' => 'Toy_Story_3.jpg', 'trailler' => 'https://www.youtube.com/embed/2BlMNH1QTeE?si=SyMQHGXWF-pMR7E1', 'calification' => 5],
                ['title_movie' => 'Pirates of the Caribbean: Dead Mans Chest', 'description_movie' => 'Jack Sparrow races to recover the heart of Davy Jones to avoid enslaving his soul to Jones service as other friends and foes seek the heart for their own agenda as well', 'release_date' => '2006-07-06', 'duration' => '2 hr 31 min', 'image' => 'Pirates_of_the_Caribbean_Dead_Mans_Chest.jpg', 'trailler' => 'https://www.youtube.com/embed/6-NGPgX-uYA?si=lzGzffuViHtBUjDD', 'calification' => 4.8],
                ['title_movie' => 'Rogue One: A Star Wars Story', 'description_movie' => 'In a time of conflict a group of unlikely heroes band together on a mission to steal the plans to the Death Star the Empires ultimate weapon of destruction', 'release_date' => '2016-12-14', 'duration' => '2 hr 13 min', 'image' => 'Rogue_One_A_Star_Wars_Story.jpg', 'trailler' => 'https://www.youtube.com/embed/frdj1zb9sMY?si=sbqdyi_p05eOpeRI', 'calification' => 3.7],
                ['title_movie' => 'Aladdin', 'description_movie' => 'A kind hearted street urchin and a power hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true', 'release_date' => '2019-05-22', 'duration' => '2 hr 8 min', 'image' => 'Aladdin.jpg', 'trailler' => 'https://www.youtube.com/embed/-G5XI61Y9ms?si=cPg6VkF1DM3vbQ8w', 'calification' => 4.7],
                ['title_movie' => 'Pirates of the Caribbean: On Stranger Tides', 'description_movie' => 'Jack Sparrow and Barbossa embark on a quest to find the elusive fountain of youth only to discover that Blackbeard and his daughter are after it too', 'release_date' => '2011-05-18', 'duration' => '2 hr 17 min', 'image' => 'Pirates_of_the_Caribbean_On_Stranger_Tides.jpg', 'trailler' => 'https://www.youtube.com/embed/0BXCVe8Yww4?si=QCuFILQIuVtZSNuY', 'calification' => 3.8],
                ['title_movie' => 'Despicable Me 3', 'description_movie' => 'Gru meets his long lost charming cheerful and more successful twin brother Dru who wants to team up with him for one last criminal heist', 'release_date' => '2017-06-14', 'duration' => '1 hr 29 min', 'image' => 'Despicable_Me_3.jpg', 'trailler' => 'https://www.youtube.com/embed/6DBi41reeF0?si=1SNnFvmDRdCvjERl', 'calification' => 4.6],
                ['title_movie' => 'Finding Dory', 'description_movie' => 'Friendly but forgetful blue tang Dory begins a search for her long lost parents and everyone learns a few things about the real meaning of family along the way', 'release_date' => '2017-06-14', 'duration' => '1 hr 29 min', 'image' => 'Finding_Dory.jpg', 'trailler' => 'https://www.youtube.com/embed/JhvrQeY3doI?si=rq80Bb0MyBSfDY8O', 'calification' => 3.4],
                ['title_movie' => 'Star Wars: Episode I - The Phantom Menace', 'description_movie' => 'Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force but the long dormant Sith resurface to claim their original glory', 'release_date' => '1999-05-19', 'duration' => '2 hr 16 min', 'image' => 'Star_Wars_Episode_I__The_Phantom_Menace.jpg', 'trailler' => 'https://www.youtube.com/embed/bD7bpG-zDJQ?si=M4AHZfFlsY3-4tRf', 'calification' => 3.6],
                ['title_movie' => 'Zootopia', 'description_movie' => 'In a city of anthropomorphic animals a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy', 'release_date' => '1999-05-19', 'duration' => '2 hr 16 min', 'image' => 'Zootopia.jpg', 'trailler' => 'https://www.youtube.com/embed/jWM0ct-OLsM?si=cd-4dt6y77S5Bh6k', 'calification' => 3.2],
                ['title_movie' => 'Alice in Wonderland', 'description_movie' => 'Nineteen year old Alice returns to the magical world from her childhood adventure where she reunites with her old friends and learns of her true destiny  - to end the Red Queens reign of terror', 'release_date' => '2010-03-03', 'duration' => '1 hr 48 min', 'image' => 'Alice_in_Wonderland.jpg', 'trailler' => 'https://www.youtube.com/embed/pMiCJefpn9Q?si=8aXLaEFhsNVY0AXP', 'calification' => 4.1],
                ['title_movie' => 'Harry Potter and the Sorcerers Stone', 'description_movie' => 'An orphaned boy enrolls in a school of wizardry where he learns the truth about himself his family and the terrible evil that haunts the magical world', 'release_date' => '2001-11-16', 'duration' => '2 hr 32 min', 'image' => 'Harry_Potter_and_the_Sorcerers_Stone.jpg', 'trailler' => 'https://www.youtube.com/embed/VyHV0BRtdxo?si=_V_PtmZVqOyJwLr4', 'calification' => 4.6],
                ['title_movie' => 'The Hobbit: An Unexpected Journey', 'description_movie' => 'A reluctant Hobbit Bilbo Baggins sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home and the gold within it from the dragon Smaug', 'release_date' => '2001-11-16', 'duration' => '2 hr 32 min', 'image' => 'The_Hobbit_An_Unexpected_Journey.jpg', 'trailler' => 'https://www.youtube.com/embed/SDnYMbYB-nU?si=xf7l6zlZfqI8Q4d8', 'calification' => 3.2],
                ['title_movie' => 'The Dark Knight', 'description_movie' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice', 'release_date' => '2008-07-16', 'duration' => '2 hr 32 min', 'image' => 'The_Dark_Knight.jpg', 'trailler' => 'https://www.youtube.com/embed/kmJLuwP3MbY?si=u-bu--EtCc7jVVJG', 'calification' => 4.2],
                ['title_movie' => 'Jurassic World Dominion', 'description_movie' => 'Four years after the destruction of Isla Nublar Biosyn operatives attempt to track down Maisie Lockwood while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects', 'release_date' => '2008-07-16', 'duration' => '2 hr 32 min', 'image' => 'Jurassic_World_Dominion.jpg', 'trailler' => 'https://www.youtube.com/embed/fb5ELWi-ekk?si=XUyZdk5rplQkUEcT" title="YouTube video player', 'calification' => 3.1],
                ['title_movie' => 'Jumanji: Welcome to the Jungle', 'description_movie' => 'Four teenagers are sucked into a magical video game and the only way they can escape is to work together to finish the game', 'release_date' => '2017-12-20', 'duration' => '1 hr 59 min', 'image' => 'Jumanji_Welcome_to_the_Jungle.jpg', 'trailler' => 'https://www.youtube.com/embed/2QKg5SZ_35I?si=aH99hymuMVgyJKjS', 'calification' => 3.9],
                ['title_movie' => 'Harry Potter and the Deathly Hallows: Part 1', 'description_movie' => 'As Harry Ron and Hermione race against time and evil to destroy the Horcruxes they uncover the existence of the three most powerful objects in the wizarding world  - the Deathly Hallows', 'release_date' => '2017-12-20', 'duration' => '1 hr 59 min', 'image' => 'Harry_Potter_and_the_Deathly_Hallows_Part_1.jpg', 'trailler' => 'https://www.youtube.com/embed/Su1LOpjvdZ4?si=G1fMtFIsBIbl4PbJ', 'calification' => 4.8],
                ['title_movie' => 'Despicable Me 2', 'description_movie' => 'When Gru the worlds most super bad turned super dad has been recruited by a team of officials to stop lethal muscle and a host of Grus own He has to fight back with new gadgetry cars and more minion madness', 'release_date' => '2013-06-20', 'duration' => '1 hr 38 min', 'image' => 'Despicable_Me_2.jpg', 'trailler' => 'https://www.youtube.com/embed/TlbnGSMJQbQ?si=WbDsTqc7oMSxB8QY', 'calification' => 4.7],
                ['title_movie' => 'The Lion King Animation', 'description_movie' => 'Lion prince Simba and his father are targeted by his bitter uncle who wants to ascend the throne himself', 'release_date' => '1994-06-15', 'duration' => '1 hr 28 min', 'image' => 'The_Lion_King_Animation.jpg', 'trailler' => 'https://www.youtube.com/embed/lFzVJEksoDY?si=8Swo5y74vb_HVZWn', 'calification' => 3.6],
                ['title_movie' => 'The Jungle Book', 'description_movie' => 'After a threat from the tiger Shere Khan forces him to flee the jungle a man cub named Mowgli embarks on a journey of self discovery with the help of panther Bagheera and free spirited bear Baloo', 'release_date' => '2016-05-07', 'duration' => '1 hr 46 min', 'image' => 'The_Jungle_Book.jpg', 'trailler' => 'https://www.youtube.com/embed/C4qgAaxB_pc?si=WrjgkkwNNK_uwCHv', 'calification' => 3.5],
                ['title_movie' => 'The Hobbit: The Battle of the Five Armies', 'description_movie' => 'Bilbo and company are forced to engage in a war against an array of combatants and keep the Lonely Mountain from falling into the hands of a rising darkness', 'release_date' => '2016-05-07', 'duration' => '1 hr 46 min', 'image' => 'The_Hobbit_The_Battle_of_the_Five_Armies.jpg', 'trailler' => 'https://www.youtube.com/embed/iVAgTiBrrDA?si=sw2uzPyAyk7Cqt5H', 'calification' => 3.5],
                ['title_movie' => 'Pirates of the Caribbean: At Worlds End', 'description_movie' => 'Captain Barbossa Will Turner and Elizabeth Swann must sail off the edge of the map navigate treachery and betrayal find Jack Sparrow and make their final alliances for one last decisive battle', 'release_date' => '2007-05-22', 'duration' => '2 hr 49 min', 'image' => 'Pirates_of_the_Caribbean_At_Worlds_End.jpg', 'trailler' => 'https://www.youtube.com/embed/HKSZtp_OGHY?si=_Trx3eMtQjdkXeu0', 'calification' => 3.3],
                ['title_movie' => 'The Hobbit: The Desolation of Smaug', 'description_movie' => 'The dwarves along with Bilbo Baggins and Gandalf the Grey continue their quest to reclaim Erebor their homeland from Smaug Bilbo Baggins is in possession of a mysterious and magical ring', 'release_date' => '2007-05-22', 'duration' => '2 hr 49 min', 'image' => 'The_Hobbit_The_Desolation_of_Smaug.jpg', 'trailler' => 'https://www.youtube.com/embed/fnaojlfdUbs?si=3DwOIOi-FIIWe1nV', 'calification' => 4.6],
                ['title_movie' => 'Doctor Strange in the Multiverse of Madness', 'description_movie' => 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses to battle multiple threats including other universe versions of himself which threaten to wipe out millions across the multiverse They seek help from Wanda the Scarlet Witch Wong and others', 'release_date' => '2007-05-22', 'duration' => '2 hr 49 min', 'image' => 'Doctor_Strange_in_the_Multiverse_of_Madness.jpg', 'trailler' => 'https://www.youtube.com/embed/aWzlQ2N6qqg?si=drRbjJpSKWzHuJdD', 'calification' => 4.5],
                ['title_movie' => 'The Lord of the Rings: The Two Towers', 'description_movie' => 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum the divided fellowship makes a stand against Saurons new ally Saruman and his hordes of Isengard', 'release_date' => '2002-12-18', 'duration' => '2 hr 59 min', 'image' => 'The_Lord_of_the_Rings_The_Two_Towers.jpg', 'trailler' => 'https://www.youtube.com/embed/LbfMDwc4azU?si=c9wNYqS4u3Zy4Ewb', 'calification' => 4.4],
                ['title_movie' => 'Harry Potter and the Order of the Phoenix', 'description_movie' => 'With their warning about Lord Voldemorts return scoffed at Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts', 'release_date' => '2007-07-11', 'duration' => '2 hr 18 min', 'image' => 'Harry_Potter_and_the_Order_of_the_Phoenix.jpg', 'trailler' => 'https://www.youtube.com/embed/y6ZW7KXaXYk?si=JaNlMav2KcT0QeR4', 'calification' => 4.4],
                ['title_movie' => 'Finding Nemo', 'description_movie' => 'After his son is captured in the Great Barrier Reef and taken to Sydney a timid clownfish sets out on a journey to bring him home', 'release_date' => '2003-05-30', 'duration' => '1 hr 40 min', 'image' => 'Finding_Nemo.jpg', 'trailler' => 'https://www.youtube.com/embed/9oQ628Seb9w?si=iWMBeBje-DKIrjP5', 'calification' => 4.7],
                ['title_movie' => 'Minions: The Rise of Gru', 'description_movie' => 'The untold story of one twelve year olds dream to become the worlds greatest supervillain', 'release_date' => '2003-05-30', 'duration' => '1 hr 40 min', 'image' => 'Minions_The_Rise_of_Gru.jpg', 'trailler' => 'https://www.youtube.com/embed/6DxjJzmYsXo?si=1dsF2-IUFJ3PTXLp', 'calification' => 4.5],
                ['title_movie' => 'Harry Potter and the Half-Blood Prince', 'description_movie' => 'As Harry Potter begins his sixth year at Hogwarts he discovers an old book marked as "the property of the Half Blood Prince" and begins to learn more about Lord Voldemorts dark past', 'release_date' => '2009-07-15', 'duration' => '2 hr 33 min', 'image' => 'Harry_Potter_and_the_HalfBlood_Prince.jpg', 'trailler' => 'https://www.youtube.com/embed/tAiy66Xrsz4?si=OmcFtJcEQCieAFup', 'calification' => 3.7],
                ['title_movie' => 'Shrek 2', 'description_movie' => 'Shrek and Fiona travel to the Kingdom of Far Far Away where Fionas parents are King and Queen to celebrate their marriage When they arrive they find they are not as welcome as they thought they would be', 'release_date' => '2004-05-19', 'duration' => '1 hr 33 min', 'image' => 'Shrek_2.jpg', 'trailler' => 'https://www.youtube.com/embed/xBgSfhp5Fxo?si=SqXd0qntO0D5MvIU', 'calification' => 4.5],
                ['title_movie' => 'Oppenheimer', 'description_movie' => 'The story of American scientist J Robert Oppenheimer and his role in the development of the atomic bomb', 'release_date' => '2004-05-19', 'duration' => '1 hr 33 min', 'image' => 'Oppenheimer.jpg', 'trailler' => 'https://www.youtube.com/embed/uYPbbksJxIg?si=mmduO0v1IYSWZwKA', 'calification' => 3.5],
                ['title_movie' => 'Harry Potter and the Chamber of Secrets', 'description_movie' => 'An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed', 'release_date' => '2002-11-14', 'duration' => '2 hr 41 min', 'image' => 'Harry_Potter_and_the_Chamber_of_Secrets.jpg', 'trailler' => 'https://www.youtube.com/embed/1bq0qff4iF8?si=gbiyoSjLRm0TP5lx', 'calification' => 4.7],
                ['title_movie' => 'Bohemian Rhapsody', 'description_movie' => 'The story of the legendary British rock band Queen and lead singer Freddie Mercury leading up to their famous performance at Live Aid', 'release_date' => '2018-10-26', 'duration' => '2 hr 14 min', 'image' => 'Bohemian_Rhapsody.jpg', 'trailler' => 'https://www.youtube.com/embed/mP0VHJYFOAU?si=yFjEi2A3T1DtK7t3', 'calification' => 3.1],
                ['title_movie' => 'The Battle at Lake Changjin', 'description_movie' => 'In the fierce battlefield in the midst of the harsh weather conditions Wu Qian Li and Wu Wan Li two brothers soldier including the brave Chinese soldiers must fight together and find a way to cope with the invasion of US forces', 'release_date' => '2018-10-26', 'duration' => '2 hr 14 min', 'image' => 'The_Battle_at_Lake_Changjin.jpg', 'trailler' => 'https://www.youtube.com/embed/7MlTVsKHoC0?si=66tNOM0rKb1DL3w6', 'calification' => 3.5],
                ['title_movie' => 'The Lord of the Rings: The Fellowship of the Ring', 'description_movie' => 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle earth from the Dark Lord Sauron', 'release_date' => '2001-12-19', 'duration' => '2 hr 58 min', 'image' => 'The_Lord_of_the_Rings_The_Fellowship_of_the_Ring.jpg', 'trailler' => 'https://www.youtube.com/embed/aStYWD25fAQ?si=WyaeXeZdEv1c1fNq', 'calification' => 4.9],
                ['title_movie' => 'Harry Potter and the Goblet of Fire', 'description_movie' => 'Harry Potter finds himself competing in a hazardous tournament between rival schools of magic but he is distracted by recurring nightmares', 'release_date' => '2005-11-16', 'duration' => '2 hr 37 min', 'image' => 'Harry_Potter_and_the_Goblet_of_Fire.jpg', 'trailler' => 'https://www.youtube.com/embed/3EGojp4Hh6I?si=1rmnjQGi22OuABBh', 'calification' => 3.9],
                ['title_movie' => 'Spider-Man 3', 'description_movie' => 'A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains temptations and revenge', 'release_date' => '2007-05-01', 'duration' => '2 hr 19 min', 'image' => 'SpiderMan_3.jpg', 'trailler' => 'https://www.youtube.com/embed/e5wUilOeOmg?si=8LrSflnx-ghytTlQ', 'calification' => 4.3],
                ['title_movie' => 'The Secret Life of Pets', 'description_movie' => 'The quiet life of a terrier named Max is upended when his owner takes in Duke a stray whom Max instantly dislikes', 'release_date' => '2016-06-24', 'duration' => '1 hr 27 min', 'image' => 'The_Secret_Life_of_Pets.jpg', 'trailler' => 'https://www.youtube.com/embed/i-80SGWfEjM?si=PEjcKZUBRZRYKIsT', 'calification' => 3.1],
                ['title_movie' => 'Ice Age: Dawn of the Dinosaurs', 'description_movie' => 'When Sids attempt to adopt three dinosaur eggs gets him abducted by their real mother to an underground lost world his friends attempt to rescue him', 'release_date' => '2009-06-29', 'duration' => '1 hr 34 min', 'image' => 'Ice_Age_Dawn_of_the_Dinosaurs.jpg', 'trailler' => 'https://www.youtube.com/embed/Y_nSwh2WjAM?si=MmXZ7M8OyuSGtYuU', 'calification' => 3.4],
                ['title_movie' => 'Spectre', 'description_movie' => 'A cryptic message from James Bonds past sends him on a trail to uncover the existence of a sinister organisation named SPECTRE With a new threat dawning Bond learns the terrible truth about the author of all his pain in his most recent missions', 'release_date' => '2015-10-26', 'duration' => '2 hr 28 min', 'image' => 'Spectre.jpg', 'trailler' => 'https://www.youtube.com/embed/ujmoYyEyDP8?si=MEdpUauanCH2Amvn', 'calification' => 5],
                ['title_movie' => 'Spider-Man: Homecoming', 'description_movie' => 'Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter ego Spider Man and finds himself on the trail of a new menace prowling the skies of New York City', 'release_date' => '2017-07-05', 'duration' => '2 hr 13 min', 'image' => 'SpiderMan_Homecoming.jpg', 'trailler' => 'https://www.youtube.com/embed/rk-dF1lIbIg?si=rzVEMoQhdMNrcTFn', 'calification' => 4.4],
                ['title_movie' => 'Ice Age: Continental Drift', 'description_movie' => 'Manny Diego and Sid embark upon another adventure after their continent is set adrift Using an iceberg as a ship they encounter sea creatures and battle pirates as they explore a new world', 'release_date' => '2012-06-27', 'duration' => '1 hr 28 min', 'image' => 'Ice_Age_Continental_Drift.jpg', 'trailler' => 'https://www.youtube.com/embed/xz-KgMtU_BM?si=lzcqL3H37aeVttdr', 'calification' => 4],
                ['title_movie' => 'Batman v Superman: Dawn of Justice', 'description_movie' => 'Batman is manipulated by Lex Luthor to fear Superman Superman´s existence is meanwhile dividing the world and he is framed for murder during an international crisis The heroes clash and force the neutral Wonder Woman to reemerge', 'release_date' => '2016-03-23', 'duration' => '2 hr 31 min', 'image' => 'Batman_v_Superman_Dawn_of_Justice.jpg', 'trailler' => 'https://www.youtube.com/embed/IwfUnkBfdZ4?si=IvOlKYaxaay2781t', 'calification' => 3.9],
                ['title_movie' => 'Wolf Warrior 2', 'description_movie' => 'Chinas deadliest special forces operative settles into a quiet life on the sea When sadistic mercenaries begin targeting nearby civilians he must leave his newfound peace behind and return to his duties as a soldier and protector', 'release_date' => '2017-07-27', 'duration' => '2 hr 3 min', 'image' => 'Wolf_Warrior_2.jpg', 'trailler' => 'https://www.youtube.com/embed/KGNAlvAZjIY?si=AbOdCXJtG-zXBRle', 'calification' => 3.5],
                ['title_movie' => 'Star Wars: Episode III - Revenge of the Sith', 'description_movie' => 'Three years into the Clone Wars Obi Wan pursues a new threat while Anakin is lured by Chancellor Palpatine into a sinister plot to rule the galaxy', 'release_date' => '2005-05-18', 'duration' => '2 hr 20 min', 'image' => 'Star_Wars_Episode_III__Revenge_of_the_Sith.jpg', 'trailler' => 'https://www.youtube.com/embed/5UnjrG_N8hU?si=9WYI6RDgzxQFSL1n', 'calification' => 3.4],
                ['title_movie' => 'The Hunger Games: Catching Fire', 'description_movie' => 'Katniss Everdeen and Peeta Mellark become targets of the Capitol after their victory in the 74th Hunger Games sparks a rebellion in the Districts of Panem', 'release_date' => '2013-11-15', 'duration' => '2 hr 26 min', 'image' => 'The_Hunger_Games_Catching_Fire.jpg', 'trailler' => 'https://www.youtube.com/embed/EAzGXqJSDJ8?si=b7Vgx27LaYdl78te', 'calification' => 4.9],
                ['title_movie' => 'Guardians of the Galaxy Vol. 2', 'description_movie' => 'The Guardians struggle to keep together as a team while dealing with their personal family issues notably Star Lords encounter with his father the ambitious celestial being Ego', 'release_date' => '2017-05-25', 'duration' => '2 hr 16 min', 'image' => 'Guardians_of_the_Galaxy_Vol_2.jpg', 'trailler' => 'https://www.youtube.com/embed/dW1BIid8Osg?si=d2yi9krjI2XZLjX5', 'calification' => 3.6],
                ['title_movie' => 'Black Panther: Wakanda Forever', 'description_movie' => 'The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King TChalla', 'release_date' => '2017-05-25', 'duration' => '2 hr 16 min', 'image' => 'Black_Panther_Wakanda_Forever.jpg', 'trailler' => 'https://www.youtube.com/embed/_Z3QKkl1WyM?si=ABNKAj_frEcfCd-G', 'calification' => 4.8],
                ['title_movie' => 'Inside Out', 'description_movie' => 'After young Riley is uprooted from her Midwest life and moved to San Francisco her emotions   Joy Fear Anger Disgust and Sadness   conflict on how best to navigate a new city house and school', 'release_date' => '2015-06-10', 'duration' => '1 hr 35 min', 'image' => 'Inside_Out.jpg', 'trailler' => 'https://www.youtube.com/embed/yRUAzGQ3nSY?si=CQ9Pl0U1HTYj-6rd', 'calification' => 3.3],
                ['title_movie' => 'Venom', 'description_movie' => 'A failed reporter is bonded to an alien entity one of many symbiotes who have invaded Earth But the being takes a liking to Earth and decides to protect it', 'release_date' => '2018-10-03', 'duration' => '1 hr 52 min', 'image' => 'Venom.jpg', 'trailler' => 'https://www.youtube.com/embed/u9Mv98Gr5pY?si=OCrkPd23ZBQrq9Sl', 'calification' => 4.2],
                ['title_movie' => 'Thor: Ragnarok', 'description_movie' => 'Imprisoned on the planet Sakaar Thor must race against time to return to Asgard and stop Ragnarök the destruction of his world at the hands of the powerful and ruthless villain Hela', 'release_date' => '2017-10-24', 'duration' => '2 hr 10 min', 'image' => 'Thor_Ragnarok.jpg', 'trailler' => 'https://www.youtube.com/embed/ue80QwXMRHg?si=CmLjEIY0Y5H5KTH7', 'calification' => 4],
                ['title_movie' => 'The Twilight Saga: Breaking Dawn - Part 2', 'description_movie' => 'After the birth of Renesmee/Nessie the Cullens gather other vampire clans in order to protect the child from a false allegation that puts the family in front of the Volturi', 'release_date' => '2012-11-14', 'duration' => '1 hr 55 min', 'image' => 'The_Twilight_Saga_Breaking_Dawn__Part_2.jpg', 'trailler' => 'https://www.youtube.com/embed/Ocz50YJOFTM?si=paP_BQY25YrEOv42', 'calification' => 4.6],
                ['title_movie' => 'Guardians of the Galaxy Vol. 3', 'description_movie' => 'Still reeling from the loss of Gamora Peter Quill rallies his team to defend the universe and one of their own   a mission that could mean the end of the Guardians if not successful', 'release_date' => '2012-11-14', 'duration' => '1 hr 55 min', 'image' => 'Guardians_of_the_Galaxy_Vol_3.jpg', 'trailler' => 'https://www.youtube.com/embed/u3V5KDHRQvk?si=G6nfhnqpVsOe2TcO', 'calification' => 4.6],
                ['title_movie' => 'Inception', 'description_movie' => 'A thief who steals corporate secrets through the use of dream sharing technology is given the inverse task of planting an idea into the mind of a CEO but his tragic past may doom the project and his team to disaster', 'release_date' => '2010-07-15', 'duration' => '2 hr 28 min', 'image' => 'Inception.jpg', 'trailler' => 'https://www.youtube.com/embed/YoHD9XEInc0?si=lfJPP6D5QoCLi2PB', 'calification' => 4.1],
                ['title_movie' => 'Transformers: Revenge of the Fallen', 'description_movie' => 'Sam Witwicky leaves the Autobots behind for a normal life But when his mind is filled with cryptic symbols the Decepticons target him and he is dragged back into the Transformers war', 'release_date' => '2009-06-19', 'duration' => '2 hr 29 min', 'image' => 'Transformers_Revenge_of_the_Fallen.jpg', 'trailler' => 'https://www.youtube.com/embed/fnXzKwUgDhg?si=EEiYMp_MytKw0yhS', 'calification' => 3.1],
                ['title_movie' => 'Spider-Man', 'description_movie' => 'After being bitten by a genetically modified spider a shy teenager gains spider like abilities that he uses to fight injustice as a masked superhero and face a vengeful enemy', 'release_date' => '2002-05-03', 'duration' => '2 hr 1 min', 'image' => 'SpiderMan.jpg', 'trailler' => 'https://www.youtube.com/embed/t06RUxPbp_c?si=K4sgCwRzGEZsPk8c', 'calification' => 5],
                ['title_movie' => 'Wonder Woman', 'description_movie' => 'When a pilot crashes and tells of conflict in the outside world Diana an Amazonian warrior in training leaves home to fight a war discovering her full powers and true destiny', 'release_date' => '2017-05-30', 'duration' => '2 hr 21 min', 'image' => 'Wonder_Woman.jpg', 'trailler' => 'https://www.youtube.com/embed/1Q8fG0TtVAY?si=DrJzTE8nBVWbhHvA', 'calification' => 5],
                ['title_movie' => 'Hi, Mom', 'description_movie' => 'A woman travels back in time to befriend her own mother in an attempt to make her life better', 'release_date' => '2017-05-30', 'duration' => '2 hr 21 min', 'image' => 'Hi_Mom.jpg', 'trailler' => 'https://www.youtube.com/embed/GjrtxkuFBtk?si=kwGcrxNFtZqonOgx', 'calification' => 3.2],
                ['title_movie' => 'Independence Day', 'description_movie' => 'The aliens are coming and their goal is to invade and destroy Earth Fighting superior technology mankinds best weapon is the will to survive', 'release_date' => '1996-07-03', 'duration' => '2 hr 25 min', 'image' => 'Independence_Day.jpg', 'trailler' => 'https://www.youtube.com/embed/B1E7h3SeMDk?si=KhtScRqDML-Ni4j2', 'calification' => 3.4],
                ['title_movie' => 'Coco', 'description_movie' => 'Aspiring musician Miguel confronted with his familys ancestral ban on music enters the Land of the Dead to find his great great grandfather a legendary singer', 'release_date' => '1996-07-03', 'duration' => '2 hr 25 min', 'image' => 'Coco.jpg', 'trailler' => 'https://www.youtube.com/embed/xlnPHQ3TLX8?si=axy9yXBkXWWYWuu_', 'calification' => 5],
                ['title_movie' => 'Fantastic Beasts and Where to Find Them', 'description_movie' => 'The adventures of writer Newt Scamander in New Yorks secret community of witches and wizards seventy years before Harry Potter reads his book in school', 'release_date' => '2016-11-16', 'duration' => '2 hr 12 min', 'image' => 'Fantastic_Beasts_and_Where_to_Find_Them.jpg', 'trailler' => 'https://www.youtube.com/embed/ViuDsy7yb8M?si=_PuxsHs2p-aRODU4', 'calification' => 3.7],
                ['title_movie' => 'Shrek the Third', 'description_movie' => 'Reluctantly designated as the heir to the land of Far Far Away Shrek hatches a plan to install the rebellious Artie as the new king while Princess Fiona tries to fend off a coup détat by the jilted Prince Charming', 'release_date' => '2007-05-17', 'duration' => '1 hr 33 min', 'image' => 'Shrek_the_Third.jpg', 'trailler' => 'https://www.youtube.com/embed/_MoIr7811Bs?si=jhFLxK3EtVhGEflx', 'calification' => 4.8],

            ]);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('movies', function (Blueprint $table) {
            DB::table('movies')->truncate();
        });
    }
};
